const data ={
    products: [
        {
            _id:'1',
            name:'Nike T-Shirt',
            category: 'Shirts',
            image:'/images/p2.jpg',
            price:120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id:'2',
            name:'Adidas T-Shirt',
            category: 'Shirts',
            image:'/images/P1.jpg',
            price:100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id:'3',
            name:'Lacoste T-Shirt',
            category: 'Shirts',
            image:'/images/p3.jpg',
            price:95,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.9,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id:'4',
            name:'Nike Pants',
            category: 'Pants',
            image:'/images/p4.jpg',
            price:120,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 11,
            description: 'High quality product',
        },
        {
            _id:'5',
            name:'Adidas Pants',
            category: 'Pants',
            image:'/images/p5.jpg',
            price:120,
            countInStock: 5,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 13,
            description: 'High quality product',
        },
        {
            _id:'6',
            name:'Puma Pants',
            category: 'Pants',
            image:'/images/p6.jpg',
            price:120,
            countInStock: 12,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 15,
            description: 'High quality product',
        },
    ]
}
export default data;